
package TestingSystem;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://Server/", className = "TestingSystem.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://Server/", className = "TestingSystem.SayHelloResponse")
    @Action(input = "http://Server/Server/sayHelloRequest", output = "http://Server/Server/sayHelloResponse")
    public String sayHello();

}
