
package TestingSystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestingSystemService", targetNamespace = "http://Server/", wsdlLocation = "http://127.0.0.1:8080/TestingSystemOganyan?wsdl")
public class TestingSystemService
    extends Service
{

    private final static URL TESTINGSYSTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTINGSYSTEMSERVICE_EXCEPTION;
    private final static QName TESTINGSYSTEMSERVICE_QNAME = new QName("http://Server/", "TestingSystemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/TestingSystemOganyan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTINGSYSTEMSERVICE_WSDL_LOCATION = url;
        TESTINGSYSTEMSERVICE_EXCEPTION = e;
    }

    public TestingSystemService() {
        super(__getWsdlLocation(), TESTINGSYSTEMSERVICE_QNAME);
    }

    public TestingSystemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTINGSYSTEMSERVICE_QNAME, features);
    }

    public TestingSystemService(URL wsdlLocation) {
        super(wsdlLocation, TESTINGSYSTEMSERVICE_QNAME);
    }

    public TestingSystemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTINGSYSTEMSERVICE_QNAME, features);
    }

    public TestingSystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestingSystemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestingSystem
     */
    @WebEndpoint(name = "TestingSystemPort")
    public TestingSystem getTestingSystemPort() {
        return super.getPort(new QName("http://Server/", "TestingSystemPort"), TestingSystem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestingSystem
     */
    @WebEndpoint(name = "TestingSystemPort")
    public TestingSystem getTestingSystemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "TestingSystemPort"), TestingSystem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTINGSYSTEMSERVICE_EXCEPTION!= null) {
            throw TESTINGSYSTEMSERVICE_EXCEPTION;
        }
        return TESTINGSYSTEMSERVICE_WSDL_LOCATION;
    }

}
